from peewee import ForeignKeyField,CompositeKey
from .base import BaseModel
from .model import Model
from .data import Data

class ModelData(BaseModel):
    """
    Represents the relationship between models and data entries.

    This junction table connects a mathematical model to experimental or
    observational data that is relevant to it.

    The relationship links a model with the data that supports, validates,
    or is generated by the model.

    Attributes:
        model (ForeignKeyField): Reference to the associated Model.
        data (ForeignKeyField): Reference to the associated Data entry.

    Relationships:
        - model.backref 'datas': Access to all data entries associated
          with a given model.
        - data.backref 'models': Access to all models associated with
          a given data entry.

    Note:
        This table uses a composite primary key (model, data) to
        ensure uniqueness. Peewee will raise an IntegrityError if you
        attempt to create a duplicate relationship.
    """
    model = ForeignKeyField(Model, backref='datas')
    data = ForeignKeyField(Data, backref='models')
    
    class Meta:
        primary_key = CompositeKey('model', 'data')